theme: jekyll-theme-minimal
title: Profile Page
description: "Welcome. This profile page contains information about me and some work samples. <br><br>CV: <a href='cv/en/cv_en.pdf'>en</a>, <a href='cv/de/cv_de.pdf'>de</a> <br><br>Contact: waackphilipp [at] gmail.com"
